<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Before\OrderController.cs">
      <Link>Controllers\BadOrderController.cs</Link>
    </Compile>
  </ItemGroup>

</Project>
